gcc:
	gcc -g -lm -Wall \
	-o ftp-with-rawsocket \
	main.c \
	main.h \
	raw_help.c \
	raw_socket.c \
	raw_file.c \
	raw_send_ls.c \
	raw_server.c \
	raw_client.c \
	raw_pack.c 
	

clean:
	rm src/*.o src/*.gch 2> /dev/null

clear:
	rm -rf *~

